version: '3.1'

services:

  db:
    image: postgres:12.3
    #image: postgres #use latest image
    ports:
     - 5432:5432 #enable external ports
    restart: always
    environment:
     - POSTGRES_PASSWORD=postgres #superuser password
     - POSTGRES_USER=postgres #superuser name
     - POSTGRES_DB=postgres
    volumes: 
     - database_data:/var/lib/postgresql/data #persist data even if container shuts down

volumes:
  database_data:
