// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/internal/handlers/orderwriter.go
//
// Generated by this command:
//
//	mockgen -source=cmd/internal/handlers/orderwriter.go -destination=cmd/internal/handlers/mocks/orderwriter_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	util "didactic-giggle/cmd/internal/util"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrderWriter is a mock of OrderWriter interface.
type MockOrderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOrderWriterMockRecorder
	isgomock struct{}
}

// MockOrderWriterMockRecorder is the mock recorder for MockOrderWriter.
type MockOrderWriterMockRecorder struct {
	mock *MockOrderWriter
}

// NewMockOrderWriter creates a new mock instance.
func NewMockOrderWriter(ctrl *gomock.Controller) *MockOrderWriter {
	mock := &MockOrderWriter{ctrl: ctrl}
	mock.recorder = &MockOrderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderWriter) EXPECT() *MockOrderWriterMockRecorder {
	return m.recorder
}

// SaveOrder mocks base method.
func (m *MockOrderWriter) SaveOrder(ctx context.Context, userID int, order string) (util.OrderSaveStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, userID, order)
	ret0, _ := ret[0].(util.OrderSaveStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderWriterMockRecorder) SaveOrder(ctx, userID, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderWriter)(nil).SaveOrder), ctx, userID, order)
}

// UpdateOrder mocks base method.
func (m *MockOrderWriter) UpdateOrder(ctx context.Context, number, status string, accrual float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, number, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderWriterMockRecorder) UpdateOrder(ctx, number, status, accrual any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderWriter)(nil).UpdateOrder), ctx, number, status, accrual)
}
