// Code generated by MockGen. DO NOT EDIT.
// Source: cmd/internal/handlers/withdraw.go
//
// Generated by this command:
//
//	mockgen -source=cmd/internal/handlers/withdraw.go -destination=cmd/internal/handlers/mocks/withdraw_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	util "didactic-giggle/cmd/internal/util"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWithdrawService is a mock of WithdrawService interface.
type MockWithdrawService struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawServiceMockRecorder
	isgomock struct{}
}

// MockWithdrawServiceMockRecorder is the mock recorder for MockWithdrawService.
type MockWithdrawServiceMockRecorder struct {
	mock *MockWithdrawService
}

// NewMockWithdrawService creates a new mock instance.
func NewMockWithdrawService(ctrl *gomock.Controller) *MockWithdrawService {
	mock := &MockWithdrawService{ctrl: ctrl}
	mock.recorder = &MockWithdrawServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawService) EXPECT() *MockWithdrawServiceMockRecorder {
	return m.recorder
}

// GetWithdrawals mocks base method.
func (m *MockWithdrawService) GetWithdrawals(ctx context.Context, userID int) ([]util.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]util.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockWithdrawServiceMockRecorder) GetWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockWithdrawService)(nil).GetWithdrawals), ctx, userID)
}

// Withdraw mocks base method.
func (m *MockWithdrawService) Withdraw(ctx context.Context, userID int, orderNumber string, amount float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, userID, orderNumber, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockWithdrawServiceMockRecorder) Withdraw(ctx, userID, orderNumber, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockWithdrawService)(nil).Withdraw), ctx, userID, orderNumber, amount)
}
